# Generated by Django 4.1.2 on 2022-11-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(default='', max_length=70, verbose_name='Nombres Completos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Apellidos'),
        ),
    ]
